# Code Generated by Sidekick is for learning and experimentation purposes only.
from django.contrib import admin
from .models import PaymentSettings, PaymentSubmission

admin.site.register(PaymentSettings)
admin.site.register(PaymentSubmission)
