# Code Generated by Sidekick is for learning and experimentation purposes only.
from django import forms
from .models import PaymentSettings, PaymentSubmission

class PaymentSettingsForm(forms.ModelForm):
    class Meta:
        model = PaymentSettings
        fields = ["upi_vpa", "qr_image", "note"]

class PaymentSubmissionForm(forms.ModelForm):
    class Meta:
        model = PaymentSubmission
        fields = ["reference_id", "payer_note"]
