# Code Generated by Sidekick is for learning and experimentation purposes only.
from django.db import models
from rentals.models import Order

class PaymentSettings(models.Model):
    upi_vpa = models.CharField(max_length=120, blank=True)
    qr_image = models.ImageField(upload_to="payments/", blank=True, null=True)
    note = models.CharField(max_length=200, blank=True)
    updated_at = models.DateTimeField(auto_now=True)

class PaymentSubmission(models.Model):
    order = models.OneToOneField(Order, on_delete=models.CASCADE, related_name="payment_submission")
    payer_note = models.CharField(max_length=200, blank=True)
    reference_id = models.CharField(max_length=120, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
