# Code Generated by Sidekick is for learning and experimentation purposes only.
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render
from rentals.models import Order
from .forms import PaymentSubmissionForm
from .models import PaymentSettings, PaymentSubmission

@login_required
def payment_page(request, order_id: int):
    order = get_object_or_404(Order, pk=order_id, customer=request.user)
    settings_obj = PaymentSettings.objects.first()
    form = PaymentSubmissionForm(request.POST or None)

    if request.method == "POST" and form.is_valid():
        PaymentSubmission.objects.update_or_create(
            order=order,
            defaults={
                "reference_id": form.cleaned_data.get("reference_id", ""),
                "payer_note": form.cleaned_data.get("payer_note", ""),
            },
        )
        order.status = Order.Status.PAYMENT_SUBMITTED
        order.save(update_fields=["status"])
        return render(request, "payments/payment_submitted.html", {"order": order})

    return render(request, "payments/payment.html", {"order": order, "ps": settings_obj, "form": form})
