# Code Generated by Sidekick is for learning and experimentation purposes only.
import os
from django.core.asgi import get_asgi_application
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "rental_platform.settings")
application = get_asgi_application()
