# Code Generated by Sidekick is for learning and experimentation purposes only.
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rentals.views import home_redirect

urlpatterns = [
    path("", home_redirect, name="home"),
    path("django-admin/", admin.site.urls),

    path("accounts/", include("allauth.urls")),
    path("auth/", include("accounts.urls")),

    path("rentals/", include("rentals.urls")),
    path("payments/", include("payments.urls")),
    path("admin-portal/", include("admin_portal.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
