# Code Generated by Sidekick is for learning and experimentation purposes only.
import os
from django.core.wsgi import get_wsgi_application
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "rental_platform.settings")
application = get_wsgi_application()
