# Code Generated by Sidekick is for learning and experimentation purposes only.
#!/usr/bin/env sh
set -e

python manage.py migrate
python manage.py collectstatic --noinput || true

gunicorn rental_platform.wsgi:application --bind 0.0.0.0:8000 --workers 2
