# Code Generated by Sidekick is for learning and experimentation purposes only.
#!/usr/bin/env sh
set -e

echo "[backend] init_db: waiting for DB, creating schema, seeding defaults..."
python -m app.init_db

echo "[backend] starting uvicorn..."
exec uvicorn app.main:app --host 0.0.0.0 --port 8000
