# Code Generated by Sidekick is for learning and experimentation purposes only.
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from app.db import get_db
from app.deps import require_role
from app.models import Tool, ToolInventory

router = APIRouter(prefix="/admin", tags=["admin"])

@router.get("/tools")
def admin_list_tools(db: Session = Depends(get_db), _=Depends(require_role("admin"))):
    tools = db.query(Tool).order_by(Tool.id.asc()).all()
    out = []
    for t in tools:
        inv = db.get(ToolInventory, t.id)
        out.append({
            "id": t.id,
            "name": t.name,
            "category": t.category,
            "description": t.description,
            "hourly_rate": t.hourly_rate,
            "image_url": t.image_url,
            "active": t.active,
            "total_qty": int(inv.total_qty) if inv else 0,
        })
    return out

@router.post("/tools", status_code=201)
def admin_create_tool(payload: dict, db: Session = Depends(get_db), _=Depends(require_role("admin"))):
    name = (payload.get("name") or "").strip()
    if not name:
        raise HTTPException(status_code=400, detail="Tool name required")

    t = Tool(
        name=name,
        category=(payload.get("category") or "general").strip(),
        description=(payload.get("description") or "").strip(),
        hourly_rate=float(payload.get("hourly_rate") or 0),
        image_url=(payload.get("image_url") or "").strip(),
        active=bool(payload.get("active", True)),
    )
    db.add(t)
    db.commit()
    db.refresh(t)

    inv = ToolInventory(tool_id=t.id, total_qty=int(payload.get("total_qty") or 0))
    db.add(inv)
    db.commit()

    return {"id": t.id}

@router.put("/tools/{tool_id}")
def admin_update_tool(tool_id: int, payload: dict, db: Session = Depends(get_db), _=Depends(require_role("admin"))):
    t = db.get(Tool, tool_id)
    if not t:
        raise HTTPException(status_code=404, detail="Not found")

    for k in ["name", "category", "description", "image_url"]:
        if k in payload and payload[k] is not None:
            setattr(t, k, str(payload[k]).strip())

    if "hourly_rate" in payload:
        t.hourly_rate = float(payload.get("hourly_rate") or 0)

    if "active" in payload:
        t.active = bool(payload.get("active"))

    if "total_qty" in payload:
        inv = db.get(ToolInventory, t.id) or ToolInventory(tool_id=t.id, total_qty=0)
        inv.total_qty = int(payload.get("total_qty") or 0)
        db.add(inv)

    db.commit()
    return {"message": "updated"}

@router.delete("/tools/{tool_id}")
def admin_delete_tool(tool_id: int, db: Session = Depends(get_db), _=Depends(require_role("admin"))):
    t = db.get(Tool, tool_id)
    if not t:
        raise HTTPException(status_code=404, detail="Not found")
    db.delete(t)
    db.commit()
    return {"message": "deleted"}
