# Code Generated by Sidekick is for learning and experimentation purposes only.
from datetime import datetime, timezone
from fastapi import APIRouter, Depends, HTTPException
from fastapi.security import OAuth2PasswordRequestForm
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import Session

from app.db import get_db, settings
from app.models import User
from app.schemas import RegisterIn, AdminRegisterIn, LoginOut
from app.security import create_access_token, hash_password, verify_password

router = APIRouter(prefix="/auth", tags=["auth"])

@router.post("/register", status_code=201)
def register_customer(payload: RegisterIn, db: Session = Depends(get_db)):
    email = payload.email.strip().lower()
    user = User(
        email=email,
        password_hash=hash_password(payload.password),
        role="customer",
        created_at=datetime.now(timezone.utc),
    )
    try:
        db.add(user)
        db.commit()
        db.refresh(user)
    except IntegrityError:
        db.rollback()
        raise HTTPException(status_code=409, detail="Email already registered")
    return {"message": "registered", "id": user.id, "role": user.role}

@router.post("/register-admin", status_code=201)
def register_admin(payload: AdminRegisterIn, db: Session = Depends(get_db)):
    if payload.admin_secret != settings.ADMIN_CREATE_SECRET:
        raise HTTPException(status_code=403, detail="Admin creation not allowed")

    email = payload.email.strip().lower()
    user = User(
        email=email,
        password_hash=hash_password(payload.password),
        role="admin",
        created_at=datetime.now(timezone.utc),
    )
    try:
        db.add(user)
        db.commit()
        db.refresh(user)
    except IntegrityError:
        db.rollback()
        raise HTTPException(status_code=409, detail="Email already registered")
    return {"message": "registered", "id": user.id, "role": user.role}

@router.post("/login", response_model=LoginOut)
def login(form: OAuth2PasswordRequestForm = Depends(), db: Session = Depends(get_db)):
    email = (form.username or "").strip().lower()
    user = db.query(User).filter(User.email == email).first()
    if not user or not verify_password(form.password, user.password_hash):
        raise HTTPException(status_code=401, detail="Invalid credentials")

    token = create_access_token(
        subject=user.email,
        role=user.role,
        user_id=user.id,
        secret=settings.JWT_SECRET,
    )
    return {
        "access_token": token,
        "token_type": "bearer",
        "role": user.role,
        "user_id": user.id,
    }
