# Code Generated by Sidekick is for learning and experimentation purposes only.
from datetime import datetime, timezone
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy import select
from sqlalchemy.orm import Session

from app.availability import available_qty
from app.db import get_db
from app.deps import get_current_user
from app.models import RentalLine, RentalOrder, ToolInventory
from app.schemas import LineIn

router = APIRouter(prefix="/orders", tags=["orders"])

@router.post("", status_code=201)
def create_order(db: Session = Depends(get_db), u=Depends(get_current_user)):
    o = RentalOrder(user_id=u.id, status="draft", created_at=datetime.now(timezone.utc))
    db.add(o)
    db.commit()
    db.refresh(o)
    return {"id": o.id, "status": o.status}

@router.post("/{order_id}/lines", status_code=201)
def add_line(order_id: int, payload: LineIn, db: Session = Depends(get_db), u=Depends(get_current_user)):
    o = db.get(RentalOrder, order_id)
    if not o or o.user_id != u.id:
        raise HTTPException(status_code=404, detail="Order not found")
    if o.status != "draft":
        raise HTTPException(status_code=400, detail="Order is not draft")
    if payload.end_ts <= payload.start_ts:
        raise HTTPException(status_code=400, detail="Invalid time window")

    avail = available_qty(db, tool_id=payload.tool_id, start_ts=payload.start_ts, end_ts=payload.end_ts)
    if payload.qty > avail:
        raise HTTPException(status_code=409, detail=f"Only {avail} available for that window")

    ln = RentalLine(
        order_id=o.id,
        tool_id=payload.tool_id,
        qty=payload.qty,
        start_ts=payload.start_ts,
        end_ts=payload.end_ts,
    )
    db.add(ln)
    db.commit()
    db.refresh(ln)
    return {"id": ln.id}

@router.post("/{order_id}/confirm")
def confirm_order(order_id: int, db: Session = Depends(get_db), u=Depends(get_current_user)):
    o = db.get(RentalOrder, order_id)
    if not o or o.user_id != u.id:
        raise HTTPException(status_code=404, detail="Order not found")
    if o.status != "draft":
        raise HTTPException(status_code=400, detail="Order not draft")

    lines = db.query(RentalLine).filter(RentalLine.order_id == o.id).all()
    if not lines:
        raise HTTPException(status_code=400, detail="No lines in order")

    # Concurrency control: lock inventory rows for involved tools, then re-check inside same txn
    tool_ids = sorted({ln.tool_id for ln in lines})
    _ = db.execute(
        select(ToolInventory)
        .where(ToolInventory.tool_id.in_(tool_ids))
        .with_for_update()
    ).scalars().all()

    for ln in lines:
        avail = available_qty(db, tool_id=ln.tool_id, start_ts=ln.start_ts, end_ts=ln.end_ts)
        if ln.qty > avail:
            raise HTTPException(status_code=409, detail=f"Only {avail} available for that window")

    o.status = "confirmed"
    db.commit()
    return {"id": o.id, "status": o.status}
