# Code Generated by Sidekick is for learning and experimentation purposes only.
from datetime import datetime
from fastapi import APIRouter, Depends, Query, HTTPException
from sqlalchemy.orm import Session

from app.availability import available_qty
from app.db import get_db
from app.models import Tool, ToolInventory
from app.schemas import ToolOut

router = APIRouter(tags=["tools"])

@router.get("/tools", response_model=list[ToolOut])
def list_tools(
    start_ts: datetime = Query(...),
    end_ts: datetime = Query(...),
    db: Session = Depends(get_db),
):
    if end_ts <= start_ts:
        raise HTTPException(status_code=400, detail="Invalid time window")

    tools = (
        db.query(Tool)
        .filter(Tool.active == True)
        .order_by(Tool.id.asc())
        .all()
    )

    out: list[ToolOut] = []
    for t in tools:
        inv = db.get(ToolInventory, t.id)
        total_qty = int(inv.total_qty) if inv else 0
        avail = available_qty(db, tool_id=t.id, start_ts=start_ts, end_ts=end_ts)
        out.append(
            ToolOut(
                id=t.id,
                name=t.name,
                category=t.category,
                description=t.description,
                hourly_rate=t.hourly_rate,
                image_url=t.image_url,
                active=t.active,
                total_qty=total_qty,
                available_qty=avail,
            )
        )
    return out
