// Code Generated by Sidekick is for learning and experimentation purposes only.
const API_BASE = "http://localhost:8000";

function token(){ return localStorage.getItem("access_token"); }
function role(){ return localStorage.getItem("role"); }

function setAuth(data){
  localStorage.setItem("access_token", data.access_token);
  localStorage.setItem("role", data.role);
  localStorage.setItem("user_id", String(data.user_id));
}
function clearAuth(){
  localStorage.removeItem("access_token");
  localStorage.removeItem("role");
  localStorage.removeItem("user_id");
}

async function login(email, password){
  const body = new URLSearchParams();
  body.set("username", email);
  body.set("password", password);

  const res = await fetch(`${API_BASE}/auth/login`, {
    method:"POST",
    headers:{ "Content-Type":"application/x-www-form-urlencoded" },
    body
  });
  if(!res.ok) throw new Error(await res.text());
  const data = await res.json();
  setAuth(data);
  return data;
}

async function registerCustomer(email, password){
  const res = await fetch(`${API_BASE}/auth/register`,{
    method:"POST",
    headers:{ "Content-Type":"application/json" },
    body: JSON.stringify({ email, password })
  });
  const ct = res.headers.get("content-type") || "";
  const payload = ct.includes("application/json") ? await res.json() : await res.text();
  if(!res.ok) throw new Error(typeof payload === "string" ? payload : (payload.detail || "Registration failed"));
  return payload;
}

async function api(path, opts={}){
  const res = await fetch(`${API_BASE}${path}`,{
    ...opts,
    headers:{
      ...(opts.headers||{}),
      ...(token() ? { Authorization:`Bearer ${token()}` } : {})
    }
  });
  const ct = res.headers.get("content-type") || "";
  const payload = ct.includes("application/json") ? await res.json() : await res.text();
  if(!res.ok) throw new Error(typeof payload === "string" ? payload : (payload.detail || "Error"));
  return payload;
}

async function listTools(startIso, endIso){
  const qs = new URLSearchParams({ start_ts: startIso, end_ts: endIso });
  return await api(`/tools?${qs.toString()}`);
}

async function createOrder(){
  return await api(`/orders`, { method:"POST" });
}

async function addLine(orderId, toolId, qty, startIso, endIso){
  return await api(`/orders/${orderId}/lines`, {
    method:"POST",
    headers:{ "Content-Type":"application/json" },
    body: JSON.stringify({ tool_id: toolId, qty, start_ts: startIso, end_ts: endIso })
  });
}

async function confirmOrder(orderId){
  return await api(`/orders/${orderId}/confirm`, { method:"POST" });
}

window.CustomerAPI = {
  token, role, setAuth, clearAuth,
  login, registerCustomer, listTools, createOrder, addLine, confirmOrder
};
