# Code Generated by Sidekick is for learning and experimentation purposes only.
from django.contrib import admin
from .models import Category, RentalItem, Order, OrderItem, CartItem

admin.site.register(Category)
admin.site.register(RentalItem)
admin.site.register(Order)
admin.site.register(OrderItem)
admin.site.register(CartItem)
