# Code Generated by Sidekick is for learning and experimentation purposes only.
from django import forms
from .models import RentalItem, Category

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ["name"]

class RentalItemForm(forms.ModelForm):
    class Meta:
        model = RentalItem
        fields = ["name", "description", "category", "daily_price", "available_qty", "image", "is_active"]

class AddToCartForm(forms.Form):
    qty = forms.IntegerField(min_value=1, initial=1)
    days = forms.IntegerField(min_value=1, initial=1)
