# Code Generated by Sidekick is for learning and experimentation purposes only.
from django.conf import settings
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=80, unique=True)

    def __str__(self):
        return self.name

class RentalItem(models.Model):
    name = models.CharField(max_length=140)
    description = models.TextField(blank=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)
    daily_price = models.DecimalField(max_digits=10, decimal_places=2)
    available_qty = models.PositiveIntegerField(default=1)
    image = models.ImageField(upload_to="items/", blank=True, null=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

class Order(models.Model):
    class Status(models.TextChoices):
        CREATED = "CREATED", "Created"
        AWAITING_PAYMENT = "AWAITING_PAYMENT", "Awaiting Payment"
        PAYMENT_SUBMITTED = "PAYMENT_SUBMITTED", "Payment Submitted"
        PAID = "PAID", "Paid"
        CANCELLED = "CANCELLED", "Cancelled"

    customer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    status = models.CharField(max_length=32, choices=Status.choices, default=Status.CREATED)
    created_at = models.DateTimeField(auto_now_add=True)

    total_amount = models.DecimalField(max_digits=12, decimal_places=2, default=0)

    def __str__(self):
        return f"Order #{self.id} ({self.status})"

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name="items")
    item = models.ForeignKey(RentalItem, on_delete=models.PROTECT)
    qty = models.PositiveIntegerField(default=1)
    days = models.PositiveIntegerField(default=1)
    unit_daily_price = models.DecimalField(max_digits=10, decimal_places=2)

    line_total = models.DecimalField(max_digits=12, decimal_places=2, default=0)

class CartItem(models.Model):
    customer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    item = models.ForeignKey(RentalItem, on_delete=models.CASCADE)
    qty = models.PositiveIntegerField(default=1)
    days = models.PositiveIntegerField(default=1)

    class Meta:
        unique_together = ("customer", "item")
