# Code Generated by Sidekick is for learning and experimentation purposes only.
from django.urls import path
from . import views

urlpatterns = [
    path("", views.item_list, name="item_list"),
    path("item/<int:item_id>/", views.item_detail, name="item_detail"),
    path("cart/", views.cart_view, name="cart"),
    path("cart/remove/<int:item_id>/", views.cart_remove, name="cart_remove"),
    path("checkout/", views.checkout, name="checkout"),
    path("orders/", views.orders_list, name="orders_list"),
    path("orders/<int:order_id>/", views.order_detail, name="order_detail"),
]
