# Code Generated by Sidekick is for learning and experimentation purposes only.
from decimal import Decimal
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.shortcuts import get_object_or_404, redirect, render

from .forms import AddToCartForm
from .models import RentalItem, CartItem, Order, OrderItem

def home_redirect(request):
    return redirect("/rentals/")

def item_list(request):
    items = RentalItem.objects.filter(is_active=True).order_by("name")
    return render(request, "rentals/item_list.html", {"items": items})

def item_detail(request, item_id: int):
    item = get_object_or_404(RentalItem, pk=item_id, is_active=True)
    form = AddToCartForm(request.POST or None)
    if request.method == "POST" and form.is_valid():
        if not request.user.is_authenticated:
            messages.info(request, "Please login to add to cart.")
            return redirect("/accounts/login/")
        qty = form.cleaned_data["qty"]
        days = form.cleaned_data["days"]

        ci, created = CartItem.objects.get_or_create(customer=request.user, item=item)
        ci.qty = qty
        ci.days = days
        ci.save()
        messages.success(request, "Added to cart.")
        return redirect("/rentals/cart/")

    return render(request, "rentals/item_detail.html", {"item": item, "form": form})

@login_required
def cart_view(request):
    cart_items = CartItem.objects.filter(customer=request.user).select_related("item")
    total = Decimal("0.00")
    for ci in cart_items:
        total += (ci.item.daily_price * ci.qty * ci.days)
    return render(request, "rentals/cart.html", {"cart_items": cart_items, "total": total})

@login_required
def cart_remove(request, item_id: int):
    CartItem.objects.filter(customer=request.user, item_id=item_id).delete()
    messages.success(request, "Removed from cart.")
    return redirect("/rentals/cart/")

@login_required
@transaction.atomic
def checkout(request):
    cart_items = list(CartItem.objects.filter(customer=request.user).select_related("item"))
    if not cart_items:
        messages.info(request, "Cart is empty.")
        return redirect("/rentals/")

    order = Order.objects.create(customer=request.user, status=Order.Status.AWAITING_PAYMENT)

    total = Decimal("0.00")
    for ci in cart_items:
        line_total = ci.item.daily_price * ci.qty * ci.days
        OrderItem.objects.create(
            order=order,
            item=ci.item,
            qty=ci.qty,
            days=ci.days,
            unit_daily_price=ci.item.daily_price,
            line_total=line_total,
        )
        total += line_total

    order.total_amount = total
    order.save(update_fields=["total_amount"])

    CartItem.objects.filter(customer=request.user).delete()

    # "Done" screen then redirect to payment page
    return render(request, "rentals/checkout_done.html", {"order": order})

@login_required
def orders_list(request):
    orders = Order.objects.filter(customer=request.user).order_by("-created_at")
    return render(request, "rentals/orders.html", {"orders": orders})

@login_required
def order_detail(request, order_id: int):
    order = get_object_or_404(Order, pk=order_id, customer=request.user)
    return render(request, "rentals/order_detail.html", {"order": order})
