# Code Generated by Sidekick is for learning and experimentation purposes only.
from django import forms
from rentals.models import RentalItem, Category
from payments.models import PaymentSettings

class RentalItemForm(forms.ModelForm):
    class Meta:
        model = RentalItem
        fields = ["name", "description", "category", "daily_price", "available_qty", "image", "is_active"]

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ["name"]

class PaymentSettingsForm(forms.ModelForm):
    class Meta:
        model = PaymentSettings
        fields = ["upi_vpa", "qr_image", "note"]
