# Code Generated by Sidekick is for learning and experimentation purposes only.
from django.urls import path
from . import views

urlpatterns = [
    path("", views.dashboard, name="admin_dashboard"),

    path("items/", views.item_list, name="admin_items"),
    path("items/new/", views.item_create, name="admin_item_create"),
    path("items/<int:item_id>/edit/", views.item_edit, name="admin_item_edit"),
    path("items/<int:item_id>/delete/", views.item_delete, name="admin_item_delete"),

    path("categories/", views.category_list, name="admin_categories"),
    path("categories/new/", views.category_create, name="admin_category_create"),

    path("orders/", views.orders, name="admin_orders"),
    path("orders/<int:order_id>/approve-payment/", views.approve_payment, name="admin_approve_payment"),

    path("payment-settings/", views.payment_settings, name="admin_payment_settings"),
]
