# Code Generated by Sidekick is for learning and experimentation purposes only.
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect, render

from accounts.models import User
from rentals.models import RentalItem, Category, Order
from payments.models import PaymentSettings
from .forms import RentalItemForm, CategoryForm, PaymentSettingsForm

def _admin_only(user) -> bool:
    return user.is_authenticated and user.role == User.Role.ADMIN

def admin_required(view):
    def _wrapped(request, *args, **kwargs):
        if not _admin_only(request.user):
            return HttpResponseForbidden("Admin only.")
        return view(request, *args, **kwargs)
    return _wrapped

@login_required
@admin_required
def dashboard(request):
    return render(request, "admin_portal/dashboard.html", {
        "items_count": RentalItem.objects.count(),
        "orders_pending": Order.objects.filter(status=Order.Status.PAYMENT_SUBMITTED).count(),
        "orders_total": Order.objects.count(),
    })

@login_required
@admin_required
def item_list(request):
    items = RentalItem.objects.all().order_by("-id")
    return render(request, "admin_portal/item_list.html", {"items": items})

@login_required
@admin_required
def item_create(request):
    form = RentalItemForm(request.POST or None, request.FILES or None)
    if request.method == "POST" and form.is_valid():
        form.save()
        messages.success(request, "Item created.")
        return redirect("/admin-portal/items/")
    return render(request, "admin_portal/item_form.html", {"form": form, "title": "Create Item"})

@login_required
@admin_required
def item_edit(request, item_id: int):
    item = get_object_or_404(RentalItem, pk=item_id)
    form = RentalItemForm(request.POST or None, request.FILES or None, instance=item)
    if request.method == "POST" and form.is_valid():
        form.save()
        messages.success(request, "Item updated.")
        return redirect("/admin-portal/items/")
    return render(request, "admin_portal/item_form.html", {"form": form, "title": "Edit Item"})

@login_required
@admin_required
def item_delete(request, item_id: int):
    item = get_object_or_404(RentalItem, pk=item_id)
    if request.method == "POST":
        item.delete()
        messages.success(request, "Item deleted.")
        return redirect("/admin-portal/items/")
    return render(request, "admin_portal/item_confirm_delete.html", {"item": item})

@login_required
@admin_required
def category_list(request):
    cats = Category.objects.all().order_by("name")
    return render(request, "admin_portal/category_list.html", {"cats": cats})

@login_required
@admin_required
def category_create(request):
    form = CategoryForm(request.POST or None)
    if request.method == "POST" and form.is_valid():
        form.save()
        messages.success(request, "Category created.")
        return redirect("/admin-portal/categories/")
    return render(request, "admin_portal/category_form.html", {"form": form, "title": "Create Category"})

@login_required
@admin_required
def orders(request):
    orders = Order.objects.all().order_by("-created_at")
    return render(request, "admin_portal/order_list.html", {"orders": orders})

@login_required
@admin_required
def approve_payment(request, order_id: int):
    order = get_object_or_404(Order, pk=order_id)
    order.status = Order.Status.PAID
    order.save(update_fields=["status"])
    messages.success(request, f"Order #{order.id} marked as PAID.")
    return redirect("/admin-portal/orders/")

@login_required
@admin_required
def payment_settings(request):
    ps = PaymentSettings.objects.first()
    form = PaymentSettingsForm(request.POST or None, request.FILES or None, instance=ps)
    if request.method == "POST" and form.is_valid():
        form.save()
        messages.success(request, "Payment settings saved.")
        return redirect("/admin-portal/payment-settings/")
    return render(request, "admin_portal/payment_settings.html", {"form": form})
