// Code Generated by Sidekick is for learning and experimentation purposes only.
const API_BASE = "http://localhost:8000";

function token(){ return localStorage.getItem("access_token"); }

function requireAdmin(){
  if(!token()) window.location.href="login.html";
  if(localStorage.getItem("role") !== "admin") window.location.href="login.html";
}

function logout(){
  localStorage.removeItem("access_token");
  localStorage.removeItem("role");
  window.location.href="login.html";
}

function toast(title, detail){
  const el = document.getElementById("toast");
  if(!el) return;
  el.querySelector(".t").textContent = title || "";
  el.querySelector(".d").textContent = detail || "";
  el.classList.add("show");
  clearTimeout(window.__toastTimer);
  window.__toastTimer = setTimeout(()=> el.classList.remove("show"), 3200);
}

function tryJson(t){ try{return JSON.parse(t);}catch{return null;} }

async function login(email,password){
  const body = new URLSearchParams();
  body.set("username", email);
  body.set("password", password);

  const res = await fetch(`${API_BASE}/auth/login`,{
    method:"POST",
    headers:{ "Content-Type":"application/x-www-form-urlencoded" },
    body
  });

  if(!res.ok) throw new Error(await res.text());
  const data = await res.json();
  localStorage.setItem("access_token", data.access_token);
  localStorage.setItem("role", data.role);
  return data;
}

async function api(path, opts={}){
  const res = await fetch(`${API_BASE}${path}`,{
    ...opts,
    headers:{
      ...(opts.headers||{}),
      Authorization:`Bearer ${token()}`
    }
  });
  if(res.ok){
    const ct = res.headers.get("content-type") || "";
    if(ct.includes("application/json")) return await res.json();
    return await res.text();
  }
  const t = await res.text();
  const j = tryJson(t);
  throw new Error(typeof j === "object" ? (j.detail?.message || j.detail || t) : t);
}

async function apiGet(path){ return await api(path); }
async function apiPost(path, json){
  return await api(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(json)});
}
async function apiPut(path, json){
  return await api(path,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(json)});
}
async function apiDelete(path){ return await api(path,{method:"DELETE"}); }

// Admin page helpers
function readForm(){
  return {
    id: document.getElementById("toolId").value.trim(),
    name: document.getElementById("name").value.trim(),
    category: document.getElementById("category").value.trim() || "general",
    hourly_rate: parseFloat(document.getElementById("hourly_rate").value || "0"),
    total_qty: parseInt(document.getElementById("total_qty").value || "0", 10),
    image_url: document.getElementById("image_url").value.trim(),
    description: document.getElementById("description").value.trim(),
    active: document.getElementById("active").value === "true",
  };
}

function fillForm(t){
  document.getElementById("toolId").value = t?.id ?? "";
  document.getElementById("name").value = t?.name ?? "";
  document.getElementById("category").value = t?.category ?? "";
  document.getElementById("hourly_rate").value = t?.hourly_rate ?? 0;
  document.getElementById("total_qty").value = t?.total_qty ?? 0;
  document.getElementById("image_url").value = t?.image_url ?? "";
  document.getElementById("description").value = t?.description ?? "";
  document.getElementById("active").value = String(!!t?.active);
  renderPreview(t?.image_url);
}

function renderPreview(url){
  const box = document.getElementById("preview");
  if(url){
    box.innerHTML = `<img src="${url}" alt="preview" />`;
  }else{
    box.innerHTML = `<div class="ph">Image preview</div>`;
  }
}

async function loadTools(){
  const q = document.getElementById("toolSearch").value.trim().toLowerCase();
  const tools = await apiGet("/admin/tools");
  const filtered = tools.filter(t =>
    !q || (t.name||"").toLowerCase().includes(q) || (t.category||"").toLowerCase().includes(q)
  );

  document.getElementById("toolCount").textContent = String(filtered.length);

  const tbody = document.getElementById("toolsTbody");
  tbody.innerHTML = filtered.map(t => `
    <tr class="click" onclick="selectTool(${t.id})">
      <td>#${t.id}</td>
      <td>${t.name}</td>
      <td><span class="pill">${t.category}</span></td>
      <td><span class="pill ${t.active ? "ok" : "bad"}">${t.active ? "Active" : "Inactive"}</span></td>
      <td>${t.total_qty}</td>
      <td>$${Number(t.hourly_rate||0).toFixed(2)}/hr</td>
    </tr>
  `).join("");
}

async function selectTool(id){
  const t = await apiGet(`/admin/tools/${id}`);
  fillForm(t);
  toast("Loaded tool", `Editing #${id}`);
}

async function saveTool(){
  const p = readForm();
  if(!p.name) return toast("Missing field","Tool name is required.");

  const payload = {
    name: p.name,
    category: p.category,
    description: p.description,
    hourly_rate: p.hourly_rate,
    image_url: p.image_url,
    active: p.active,
    total_qty: p.total_qty
  };

  if(!p.id){
    const r = await apiPost("/admin/tools", payload);
    toast("Created", `Tool #${r.id} created.`);
    await loadTools();
    await selectTool(r.id);
    return;
  }

  await apiPut(`/admin/tools/${p.id}`, payload);
  toast("Saved", `Tool #${p.id} updated.`);
  await loadTools();
}

async function deleteTool(){
  const id = document.getElementById("toolId").value.trim();
  if(!id) return toast("Nothing selected","Pick a tool first.");
  if(!confirm(`Delete tool #${id}?`)) return;

  await apiDelete(`/admin/tools/${id}`);
  fillForm(null);
  toast("Deleted", `Tool #${id} deleted.`);
  await loadTools();
}

// Code Generated by Sidekick is for learning and experimentation purposes only.
async function register(email, password) {
  const res = await fetch(`${API_BASE}/auth/register`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ email, password })
  });

  if (!res.ok) throw new Error(await res.text());
  return await res.json();
}


async function loadOrders(){
  const status = document.getElementById("orderFilter").value;
  const orders = await apiGet("/admin/orders");
  const filtered = orders.filter(o => status === "all" || o.status === status);

  document.getElementById("orderCount").textContent = String(filtered.length);

  const el = document.getElementById("orders");
  el.innerHTML = filtered.map(o => `
    <div style="border:1px solid rgba(255,255,255,.12);background:rgba(255,255,255,.04);border-radius:16px;padding:12px;margin-bottom:10px;">
      <div class="row" style="align-items:center;">
        <div style="flex:1 1 auto;">
          <div style="font-weight:950;">Order #${o.id} <span class="pill">${o.status}</span></div>
          <div class="helper" style="margin-top:4px;">User: ${o.user_id} • Created: ${o.created_at}</div>
        </div>
        <div><span class="pill">Lines: ${(o.lines||[]).length}</span></div>
      </div>
      <div class="hr"></div>
      <pre style="margin:0;white-space:pre-wrap;color:rgba(242,246,255,.84);font-size:12px;">${JSON.stringify(o.lines||[], null, 2)}</pre>
    </div>
  `).join("");
}

// expose for onclick
window.logout = logout;
window.loadTools = loadTools;
window.selectTool = selectTool;
window.saveTool = saveTool;
window.deleteTool = deleteTool;
window.loadOrders = loadOrders;
window.renderPreview = renderPreview;
