// Code Generated by Sidekick is for learning and experimentation purposes only.
const API_BASE = "http://localhost:8000";

function token(){ return localStorage.getItem("access_token"); }
function role(){ return localStorage.getItem("role"); }

function setAuth(data){
  localStorage.setItem("access_token", data.access_token);
  localStorage.setItem("role", data.role);
  localStorage.setItem("user_id", String(data.user_id));
}
function clearAuth(){
  localStorage.removeItem("access_token");
  localStorage.removeItem("role");
  localStorage.removeItem("user_id");
}

async function login(email, password){
  const body = new URLSearchParams();
  body.set("username", email);
  body.set("password", password);

  const res = await fetch(`${API_BASE}/auth/login`, {
    method:"POST",
    headers:{ "Content-Type":"application/x-www-form-urlencoded" },
    body
  });
  if(!res.ok) throw new Error(await res.text());
  const data = await res.json();
  setAuth(data);
  return data;
}

async function registerAdmin(email, password, adminSecret){
  const res = await fetch(`${API_BASE}/auth/register-admin`,{
    method:"POST",
    headers:{ "Content-Type":"application/json" },
    body: JSON.stringify({ email, password, admin_secret: adminSecret })
  });
  const ct = res.headers.get("content-type") || "";
  const payload = ct.includes("application/json") ? await res.json() : await res.text();
  if(!res.ok) throw new Error(typeof payload === "string" ? payload : (payload.detail || "Registration failed"));
  return payload;
}

async function api(path, opts={}){
  const res = await fetch(`${API_BASE}${path}`,{
    ...opts,
    headers:{
      ...(opts.headers||{}),
      Authorization:`Bearer ${token()}`
    }
  });
  const ct = res.headers.get("content-type") || "";
  const payload = ct.includes("application/json") ? await res.json() : await res.text();
  if(!res.ok) throw new Error(typeof payload === "string" ? payload : (payload.detail || "Error"));
  return payload;
}

async function adminListTools(){ return await api(`/admin/tools`); }
async function adminCreateTool(p){
  return await api(`/admin/tools`, {
    method:"POST",
    headers:{ "Content-Type":"application/json" },
    body: JSON.stringify(p)
  });
}
async function adminUpdateTool(id,p){
  return await api(`/admin/tools/${id}`, {
    method:"PUT",
    headers:{ "Content-Type":"application/json" },
    body: JSON.stringify(p)
  });
}
async function adminDeleteTool(id){
  return await api(`/admin/tools/${id}`, { method:"DELETE" });
}

window.AdminAPI = { token, role, setAuth, clearAuth, login, registerAdmin, adminListTools, adminCreateTool, adminUpdateTool, adminDeleteTool };
