# Code Generated by Sidekick is for learning and experimentation purposes only.
from django.contrib import admin
from django.contrib.auth import get_user_model
from .models import WhatsAppOTP

User = get_user_model()

@admin.register(User)
class UserAdmin(admin.ModelAdmin):
    list_display = ("email", "role", "is_staff", "is_active", "date_joined")
    search_fields = ("email",)
    list_filter = ("role", "is_staff", "is_active")

@admin.register(WhatsAppOTP)
class WhatsAppOTPAdmin(admin.ModelAdmin):
    list_display = ("phone", "created_at", "expires_at", "consumed_at")
    search_fields = ("phone",)
