# Code Generated by Sidekick is for learning and experimentation purposes only.
from django.apps import AppConfig

class AccountsConfig(AppConfig):
    default_auto_field = "django.db.models.BigAutoField"
    name = "accounts"
