# Code Generated by Sidekick is for learning and experimentation purposes only.
from django import forms
from django.contrib.auth import get_user_model

User = get_user_model()

class SetupAdminForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ["email", "first_name", "last_name"]

class WhatsAppStartForm(forms.Form):
    phone = forms.CharField(max_length=30, help_text="Include country code, e.g., +91...")

class WhatsAppVerifyForm(forms.Form):
    phone = forms.CharField(max_length=30)
    code = forms.CharField(max_length=6)
