# Code Generated by Sidekick is for learning and experimentation purposes only.
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone
import hashlib
import secrets

class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True)

    class Role(models.TextChoices):
        ADMIN = "ADMIN", "Admin"
        CUSTOMER = "CUSTOMER", "Customer"

    role = models.CharField(max_length=20, choices=Role.choices, default=Role.CUSTOMER)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

class WhatsAppOTP(models.Model):
    phone = models.CharField(max_length=30)
    code_hash = models.CharField(max_length=64)
    created_at = models.DateTimeField(auto_now_add=True)
    expires_at = models.DateTimeField()
    consumed_at = models.DateTimeField(null=True, blank=True)

    @staticmethod
    def generate_code() -> str:
        return f"{secrets.randbelow(10**6):06d}"

    @staticmethod
    def hash_code(code: str) -> str:
        return hashlib.sha256(code.encode("utf-8")).hexdigest()

    def is_valid(self, code: str) -> bool:
        if self.consumed_at is not None:
            return False
        if timezone.now() > self.expires_at:
            return False
        return self.code_hash == self.hash_code(code)
