# Code Generated by Sidekick is for learning and experimentation purposes only.
from django.urls import path
from . import views

urlpatterns = [
    path("setup-admin/", views.setup_admin, name="setup_admin"),
    path("whatsapp/start/", views.whatsapp_start, name="whatsapp_start"),
    path("whatsapp/verify/", views.whatsapp_verify, name="whatsapp_verify"),
]
