# Code Generated by Sidekick is for learning and experimentation purposes only.
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import login, get_user_model
from django.http import HttpResponseForbidden
from django.shortcuts import redirect, render
from django.utils import timezone
from django.views.decorators.http import require_http_methods
import requests

from .forms import SetupAdminForm, WhatsAppStartForm, WhatsAppVerifyForm
from .models import WhatsAppOTP

User = get_user_model()

def _any_admin_exists() -> bool:
    return User.objects.filter(role=User.Role.ADMIN).exists()

@require_http_methods(["GET", "POST"])
def setup_admin(request):
    # Allow only once: first admin registration
    if _any_admin_exists():
        return HttpResponseForbidden("Admin already exists.")

    form = SetupAdminForm(request.POST or None)
    if request.method == "POST" and form.is_valid():
        email = form.cleaned_data["email"].lower()
        password = form.cleaned_data["password"]

        user = User(
            email=email,
            first_name=form.cleaned_data.get("first_name", ""),
            last_name=form.cleaned_data.get("last_name", ""),
            role=User.Role.ADMIN,
            is_staff=True,
            is_superuser=False,
        )
        user.set_password(password)
        user.save()

        login(request, user)
        messages.success(request, "Admin created. Welcome to the Admin Portal.")
        return redirect("/admin-portal/")

    return render(request, "accounts/setup_admin.html", {"form": form})

def _send_whatsapp_otp(phone: str, code: str) -> None:
    # WhatsApp Cloud API: send OTP via an approved authentication template. [^2^](https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQE2QMpWwXB2BQN8Vems9w8hpsmWSruAoENRjzyBMhc4rO6K0IAeqK9w33yOealJhVjcfqpVx8BKjMwa5fv78SaYL3CgoZlJvdsjL5c8wTNI7MAuSrh7NOD9HVpXsWHAoENrh_SHDaupnMijx1yy1KbUsjg6_VGfSHkxgae9r95bNhiaQ58uYsv2kbb1I0jy7ZCaJ3vWyEiAtju0kqdf2-sUw_Sjo_Rc17T7INL4UKtKUe-61JnYJf-JDiCyqmYoeOn7vw==)
    if not (settings.WHATSAPP_TOKEN and settings.WHATSAPP_PHONE_NUMBER_ID and settings.WHATSAPP_OTP_TEMPLATE_NAME):
        raise RuntimeError("WhatsApp config missing.")

    url = f"https://graph.facebook.com/v20.0/{settings.WHATSAPP_PHONE_NUMBER_ID}/messages"
    headers = {"Authorization": f"Bearer {settings.WHATSAPP_TOKEN}", "Content-Type": "application/json"}

    payload = {
        "messaging_product": "whatsapp",
        "to": phone.replace("+", ""),
        "type": "template",
        "template": {
            "name": settings.WHATSAPP_OTP_TEMPLATE_NAME,
            "language": {"code": settings.WHATSAPP_LANGUAGE_CODE},
            "components": [
                {"type": "body", "parameters": [{"type": "text", "text": code}]}
            ],
        },
    }

    r = requests.post(url, json=payload, headers=headers, timeout=20)
    r.raise_for_status()

@require_http_methods(["GET", "POST"])
def whatsapp_start(request):
    form = WhatsAppStartForm(request.POST or None)
    if request.method == "POST" and form.is_valid():
        phone = form.cleaned_data["phone"].strip()

        code = WhatsAppOTP.generate_code()
        otp = WhatsAppOTP.objects.create(
            phone=phone,
            code_hash=WhatsAppOTP.hash_code(code),
            expires_at=timezone.now() + timezone.timedelta(minutes=5),
        )

        try:
            _send_whatsapp_otp(phone, code)
        except Exception as e:
            otp.delete()
            messages.error(request, f"Failed to send WhatsApp OTP: {e}")
            return redirect("/auth/whatsapp/start/")

        messages.success(request, "OTP sent on WhatsApp.")
        return redirect(f"/auth/whatsapp/verify/?phone={phone}")

    return render(request, "accounts/whatsapp_start.html", {"form": form})

@require_http_methods(["GET", "POST"])
def whatsapp_verify(request):
    initial_phone = request.GET.get("phone", "")
    form = WhatsAppVerifyForm(request.POST or None, initial={"phone": initial_phone})

    if request.method == "POST" and form.is_valid():
        phone = form.cleaned_data["phone"].strip()
        code = form.cleaned_data["code"].strip()

        otp = WhatsAppOTP.objects.filter(phone=phone).order_by("-created_at").first()
        if not otp or not otp.is_valid(code):
            messages.error(request, "Invalid or expired OTP.")
            return redirect(f"/auth/whatsapp/verify/?phone={phone}")

        otp.consumed_at = timezone.now()
        otp.save(update_fields=["consumed_at"])

        # Create or login a CUSTOMER user using phone as email surrogate if needed
        email = f"{phone.replace('+','') }@whatsapp.local"
        user, created = User.objects.get_or_create(email=email, defaults={"role": User.Role.CUSTOMER})
        if created:
            user.set_unusable_password()
            user.save()

        login(request, user)
        messages.success(request, "Logged in via WhatsApp OTP.")
        return redirect("/rentals/")

    return render(request, "accounts/whatsapp_verify.html", {"form": form})
