# Code Generated by Sidekick is for learning and experimentation purposes only.
from datetime import datetime
from sqlalchemy import func, select
from sqlalchemy.orm import Session

from app.models import RentalLine, RentalOrder, ToolInventory

def overlap_clause(start_ts: datetime, end_ts: datetime):
    # half-open overlap: requested_start < existing_end AND requested_end > existing_start
    return (RentalLine.start_ts < end_ts) & (RentalLine.end_ts > start_ts)

def available_qty(db: Session, *, tool_id: int, start_ts: datetime, end_ts: datetime) -> int:
    inv = db.get(ToolInventory, tool_id)
    total_qty = int(inv.total_qty) if inv else 0

    booked = db.execute(
        select(func.coalesce(func.sum(RentalLine.qty), 0))
        .join(RentalOrder, RentalOrder.id == RentalLine.order_id)
        .where(RentalLine.tool_id == tool_id)
        .where(RentalOrder.status == "confirmed")
        .where(overlap_clause(start_ts, end_ts))
    ).scalar_one()

    return max(0, total_qty - int(booked))
