# Code Generated by Sidekick is for learning and experimentation purposes only.
from pydantic_settings import BaseSettings
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

class Settings(BaseSettings):
    DATABASE_URL: str
    JWT_SECRET: str = "change-me"
    ADMIN_CREATE_SECRET: str = "admin-create-secret"
    CORS_ORIGINS: str = "http://localhost:5500"

    DEFAULT_ADMIN_EMAIL: str = "admin@example.com"
    DEFAULT_ADMIN_PASSWORD: str = "admin123"
    DEFAULT_CUSTOMER_EMAIL: str = "user@example.com"
    DEFAULT_CUSTOMER_PASSWORD: str = "user1234"

settings = Settings()

engine = create_engine(settings.DATABASE_URL, pool_pre_ping=True)
SessionLocal = sessionmaker(bind=engine, autoflush=False, autocommit=False)

def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
