# Code Generated by Sidekick is for learning and experimentation purposes only.
import time
from datetime import datetime, timezone

from sqlalchemy import text
from sqlalchemy.exc import OperationalError
from sqlalchemy.orm import Session

from app.db import SessionLocal, engine, settings
from app.models import Base, User
from app.security import hash_password

def wait_for_db(max_seconds: int = 90):
    start = time.time()
    while True:
        try:
            with engine.connect() as conn:
                conn.execute(text("SELECT 1"))
            return
        except OperationalError:
            if time.time() - start > max_seconds:
                raise
            time.sleep(1)

def ensure_user(db: Session, *, email: str, password: str, role: str):
    email_n = (email or "").strip().lower()
    if not email_n or not password:
        return

    exists = db.query(User).filter(User.email == email_n).first()
    if exists:
        return

    u = User(
        email=email_n,
        password_hash=hash_password(password),
        role=role,
        created_at=datetime.now(timezone.utc),
    )
    db.add(u)
    db.commit()

def main():
    wait_for_db()
    Base.metadata.create_all(bind=engine)

    db = SessionLocal()
    try:
        ensure_user(
            db,
            email=settings.DEFAULT_ADMIN_EMAIL,
            password=settings.DEFAULT_ADMIN_PASSWORD,
            role="admin",
        )
        ensure_user(
            db,
            email=settings.DEFAULT_CUSTOMER_EMAIL,
            password=settings.DEFAULT_CUSTOMER_PASSWORD,
            role="customer",
        )
    finally:
        db.close()

if __name__ == "__main__":
    main()
