# Code Generated by Sidekick is for learning and experimentation purposes only.
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.db import settings
from app.routers import auth, tools, orders, admin

app = FastAPI(title="Rental API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=[o.strip() for o in settings.CORS_ORIGINS.split(",") if o.strip()],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(auth.router)
app.include_router(tools.router)
app.include_router(orders.router)
app.include_router(admin.router)

@app.get("/health")
def health():
    return {"ok": True}
