# Code Generated by Sidekick is for learning and experimentation purposes only.
from datetime import datetime
from pydantic import BaseModel, EmailStr, Field

class RegisterIn(BaseModel):
    email: EmailStr
    password: str = Field(min_length=6, max_length=200)

class AdminRegisterIn(RegisterIn):
    admin_secret: str

class LoginOut(BaseModel):
    access_token: str
    token_type: str = "bearer"
    role: str
    user_id: int

class ToolOut(BaseModel):
    id: int
    name: str
    category: str
    description: str
    hourly_rate: float
    image_url: str
    active: bool
    total_qty: int
    available_qty: int

class LineIn(BaseModel):
    tool_id: int
    qty: int = Field(gt=0)
    start_ts: datetime
    end_ts: datetime
