# Code Generated by Sidekick is for learning and experimentation purposes only.
@router.get("/{order_id}")
def get_order(order_id: int, db: Session = Depends(get_db), user: User = Depends(get_current_user)):
    order = (
        db.query(RentalOrder)
        .filter(RentalOrder.id == order_id, RentalOrder.user_id == user.id)
        .first()
    )
    if not order:
        raise HTTPException(status_code=404, detail="Order not found")

    return {
        "id": order.id,
        "status": order.status,
        "lines": [
            {
                "id": l.id,
                "tool_id": l.tool_id,
                "tool_name": l.tool.name if l.tool else None,
                "hourly_rate": float(l.tool.hourly_rate) if l.tool else None,
                "image_url": l.tool.image_url if l.tool else "",
                "qty": l.qty,
                "start_ts": l.start_ts.isoformat(),
                "end_ts": l.end_ts.isoformat(),
            }
            for l in order.lines
        ],
    }


# Code Generated by Sidekick is for learning and experimentation purposes only.
@router.delete("/{order_id}/lines/{line_id}")
def delete_line(order_id: int, line_id: int, db: Session = Depends(get_db), user: User = Depends(get_current_user)):
    order = (
        db.query(RentalOrder)
        .filter(RentalOrder.id == order_id, RentalOrder.user_id == user.id)
        .first()
    )
    if not order:
        raise HTTPException(status_code=404, detail="Order not found")
    if order.status != "draft":
        raise HTTPException(status_code=400, detail="Only draft orders can be edited")

    line = db.query(RentalLine).filter(RentalLine.id == line_id, RentalLine.order_id == order.id).first()
    if not line:
        raise HTTPException(status_code=404, detail="Line not found")

    db.delete(line)
    db.commit()
    return {"message": "line deleted"}
