# Code Generated by Sidekick is for learning and experimentation purposes only.
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="RentalItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=140)),
                ("description", models.TextField(blank=True)),
                ("daily_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("available_qty", models.PositiveIntegerField(default=1)),
                ("image", models.ImageField(blank=True, null=True, upload_to="items/")),
                ("is_active", models.BooleanField(default=True)),
                ("category", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="rentals.category")),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("CREATED", "Created"), ("AWAITING_PAYMENT", "Awaiting Payment"), ("PAYMENT_SUBMITTED", "Payment Submitted"), ("PAID", "Paid"), ("CANCELLED", "Cancelled")], default="CREATED", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("total_amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("qty", models.PositiveIntegerField(default=1)),
                ("days", models.PositiveIntegerField(default=1)),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="rentals.rentalitem")),
            ],
            options={"unique_together": {("customer", "item")}},
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("qty", models.PositiveIntegerField(default=1)),
                ("days", models.PositiveIntegerField(default=1)),
                ("unit_daily_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("line_total", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="rentals.rentalitem")),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="rentals.order")),
            ],
        ),
    ]
